package org.academiadecodigo.gitbusters;

public class Image {

    public static String imageGuess = "\n" +
            "\n" +
            "      .__                                                                            \n" +
            "      |__| _____ _____     ____   ____             ____  __ __   ____   ______ ______\n" +
            "      |  |/     \\\\__  \\   / ___\\_/ __ \\   ______  / ___\\|  |  \\_/ __ \\ /  ___//  ___/\n" +
            "      |  |  Y Y  \\/ __ \\_/ /_/  >  ___/  /_____/ / /_/  >  |  /\\  ___/ \\___ \\ \\___ \\ \n" +
            "      |__|__|_|  (____  /\\___  / \\___  >         \\___  /|____/  \\___  >____  >____  >\n" +
            "               \\/     \\//_____/      \\/         /_____/             \\/     \\/     \\/ \n" +
            "\n";


    public static String separator = "\n" +
            "\n" +
            " ____________________________________________________________________________________\n" +
            "/_____/_____/_____/_____/_____/_____/_____/_____/_____/_____/_____/_____/_____/_____/\n" +
            "\n";

    public static String ghost = "XXXXXNNXXXXNXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXNXXXXNXXNXXXXXXXXXXXXXNXXNNXXXXXXXXX\n" +
            "NXXNXXXXXXNXXNXXXXXXXXXXXXNNXXNXXXXXNXXXXNNXXXXNNXXXXXNXXXXXXXXXXXXXNXXNXXXXXXXX\n" +
            "XXXXXXXXNNXXXXXXXXNXXXNXXXXNNXXNXXXNXXXXXKKXXXNXXXXXXXXXXXXNXXXNXXXXXNXXXNXXXXXN\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0xolccccllccldk0XXXXXXXXXXXNXXNXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKxc:coxkO0000Okdoc:cxKXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd;:d0XXXNXXXXXXNNXX0o;;xXXXXXXXXXXXXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXNXXNXXXNXNXXXXXXXX0c,dKXXK0KXXXXXXXXXXNXX0l,oKXXXXXNXXNXXXXXXXXXXXXXXX\n" +
            "XXXXXXXXXXXXXXXNXXXXXXXXXXX0:,kXXXXX00XXXXXXXXK0KXXXXd,dXXXNXXXXXXXXXXXXXXXXXXXN\n" +
            "XXXXXXXXXXKkdk0XNNXNNXXNXXXo,xXXXXN0oo0XNXXXXKO0XXXNXK:;ONXXXXXXXXXXXXXXXXXXXXNX\n" +
            "XXXXXXXX0d;,cc:llcokKXNXXNO,:KXXXXXx':0NXXXXKl.lKXXXXXo,xXXXXXNXXXXKkdoxKNXXXNXX\n" +
            "XNXXXXX0;'lkKXOlcoc,dXXXXXd,oXXXXXXX0KXXXXXXXkokXNXXNXo,xXXXXN0occ:::oc,;o0XXXXX\n" +
            "NXXXXXXo'oKXXNXXXX0c,dKXXKc,kXXXXXXXXNXXNXXXXXXXXXXXXXo,xNXXXKc;xxlxKXKOl'cKXXXX\n" +
            "XXXXXNXx,c0XXXXXXXXKl'ckKk,cKXXXXXXKXXXXXXXXXXXXXXXXNXo,xXXNO:;xXXXXXXXX0c,kXXXX\n" +
            "NXXXXXNKl;ldxOKXXNXXKkl::';kXXNXXNXkxOKXXNXX0O0XXXXNXXx,oKOo,;kXXXXXXXXXk;:0XXNX\n" +
            "XXXXXXNNKkdlc:cdOKXXXXXKkdkXXXXXXXXKkolllllookKXXXXXXXO,'c:cd0XXXXXXOxooc:xXNNXX\n" +
            "XXXXXXXXNNXXXKkoccclx0XXNXXXXXXXXXXXXXKOkkk0XXXXXXXXXNKxokKXXXXXKOdcclodkKXXXXXX\n" +
            "XXXNXXXXXXNXXNNXX0kdlccd0XXXXXNXXNXXNXXNNNXXNXXXXXXNXXXXXNXX0xlccccx0XXXXXXXXNXX\n" +
            "XXXXXNXXXXXXXXXNXXXNXd':0XNXXXXXNXXNXXNNXXXNXXXXXNNXXXXXXOoc:ldO0XXXXXXXXNXXXXXN\n" +
            "XXXXXXNNXXXXXXXXXNXKd;lKNXXNXXXXXXXXXNXXNXXXXXXXXXNNXXNXKl.:0XXXNXXXNXXXXXNXXXNX\n" +
            "XXXXXXXXXXXXXXXXXX0l,dKXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXX0c;OXXXXXXXXXXXXXXXXNXX\n" +
            "XXXXXXXXXXXXXXXNKd;:kXXXXXXXNXXXXXXXXXNXXXXNXXNXXXXXXXXXXXO::OXXXXXXXNXXXXXXXXXX\n" +
            "XXXNXXXXXXNNXXKd:;dKNXXXXXXXXXNXXNXXNXXXXNXXNXXXXXXXXXXXXXXk;;OXXXXXXXXNXXNXXXXX\n" +
            "XXXXXNXXXXXX0o;:d0NXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXk;:OXXNXXNXXXXXXNXXX\n" +
            "XXXXXXXXXX0l;:xKXXXXXXXNXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXO;:OXXXXXXNXXXXXXXX\n" +
            "XNXXXXXX0o;ckKNXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO;,kXXXXXXXXNNXXXX\n" +
            "XXXXXXKd;:xXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0c,dXNXXXXXXNNXXX\n" +
            "NXXXN0l,oKNXXXXXXXXXNXK0kk0XXXNXXXXXXXXXNXXXXXXXXXXNXXXXXXXXXXXXKo,oKXNXXXXXXNXX\n" +
            "XNXXKl,xXXXXXXXXXXXOoccclc:cOXXXXXXNXXXXXXXXXXXXXNNXXXXXNXXNNXXXXXx;l0XXXXXXNXXN\n" +
            "XXXNx,oXXXXXXXXKOoc:ld0XXX0:;kXXXXXXXXXXNXXXNXXXXK00KXXXXNXXXNXXXNXk;;kXXXNXXXXX\n" +
            "XXNXx,:0XXXX0xlccox0XXXXXXXO;;OXXXXXXXXNXXXNXXXOocccclxKXXXNXXXXXXXX0c,dKXXXXXXX\n" +
            "XXXXXkc:cllcccoOKXXXXNNXXNXXk;c0XXXXXXXXXXXXX0o;ckKKOd:;lkXXXXXXXXXXXKo,oKXXXXXX\n" +
            "XXXXXXX0kkO0KXXXXXXXXXXXXXXXXx,c0XXXXXXXXXX0o;:kXXXXXXXkl;:oOXNXXXXNXXXd,oKXXXXX\n" +
            "XXNXXNXXNNXXNXXXXXXXXXXXXNXXXXx;;xKNXXNK0kl:cxXXXXXXXNXXX0xc:cok0XXXXNXO,;0XNXXX\n" +
            "NXXNXXXXXXNXXXXXXXXXXXXXXXXXXXX0o::looc:::lkXXXNXXXXXXNXXXXXKkoccclllll:ckXXXXNX\n" +
            "XXXXXXXXXXXXXXXXXXXXNXXXXXXXNXXXXKOddddk0KXXXXXXXXXXXXXXXXXXXNXXKOkxxxk0XXXXXXXX\n" +
            "XXXXXNNXXXXNNXXXXXXXXXXXXNXXXXXXXXXNXXXXXXXXXXXXXXXNNXXXXXXXXXXXXXNXXNXXXXXXNXXX\n" +
            "NXXXXXXNXXNXXNXXXXXXXXXNXXXXXXXXXXXXXNXXNXXXXXXXXXXXXNNXXXXXXXXXXXXXXXXXXXNXXXXX\n";

    public static String moustache = "MWWWMWWMWWWMWWWWWWMWWWMWWMWWWMWWWMWWMWWWMMWWWMWWMWWWMWWWWWWMWWWMWWMWWWMWWWMWWMWW\n" +
            "WWWWWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWW\n" +
            "WWWWWWWKd:'.';oKWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWKo;'',:dKWWWWWWW\n" +
            "WWWWWXo.       ;KWWWWWWWWWNKOddoodOXWWWWWWWWXOxdodxOKNWWWWWWWWWK;       .lXWWWWW\n" +
            "WWWWK;  'okOx, .kWWWWWWKxl,.       .:xXWMXx:.       .,lxKNWWWWWk. ,xOko,  ;KWWWW\n" +
            "WWWX:  ,KWWWWk.,KWWXOo;.              ,oo,              .;oOXWMK,.xWWWWK,  :XWWW\n" +
            "WWWd   ,0WWWW0lxOdc'                                        ':d0xlOWWWMK,   oWWW\n" +
            "WWX;    .lxxxo:'.                                              .':lxkxl'    ;XWW\n" +
            "WWNc                                  .;;.                                  cNWW\n" +
            "WWW0,                               .:ONW0c.                               'OWWW\n" +
            "WWWW0:                           'cxKWWWWWWKxc'                           :0WWWW\n" +
            "WWWWWNOl'.                 ..,cdOXWWWWWWWWWWWWNOdc,..                 .'cONWWWWW\n" +
            "WWWWWWWWN0kdolc::::::cclodk0XNWWWWWWWWWWWWWWWWWWWWWX0kxolcc::::::clodk0NWWWWWWWW\n" +
            "MWWWWWWMWWWMWWMMWWMWWMMWWMWWWMWWWWWWMWWWMMWWWWWWMWWWWWWMMWWMWWWMWWMMWWMWWWWWWMWW\n";

    public static String key = "MMMMMMMMMMWXkdoox0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMWKl..';,'.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMM0, :ONWWXx..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMWNXo 'OMMMMMWo ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMW0l;'.. .oNMMMW0; :XMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MNd..;dxo;;xOkkx:. .;ll;'ckKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000K0KX00NMM\n" +
            "MK, cNMMMWWK,              ..................................................cXM\n" +
            "MX: 'kXWXkk0o,;'    ...  .;ccccccccccccc::::::::::::::::::::::;,.    .,;;:c;;xNM\n" +
            "MMKl...'. .oNWWNOl..c0KkdOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:;;'     .,;;c0WWMMM\n" +
            "MMMWXkdo, .OMMMMMNl ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;            :KMMMMM\n" +
            "MMMMMMMMx..xWMMMMX: ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'   .    .   ,OMMMMM\n" +
            "MMMMMMMMNo..:dkxo,.,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   ;k;  :k,  .xMMMMM\n" +
            "MMMMMMMMMW0o;,'',cxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;',xXd,,xXo'':0MMMMM\n" +
            "MMMMMMMMMMMMWXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMWNNWMNNNNWMMMMM\n";

    public static String camera = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXNXXXXNXXXXNXXXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOddxxxxxxxxxxxxxxxxokNWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWNklONWNxdxxxxxxxxdkNW0lxNWWWWWWXKKXWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWKdoKWWWKlo00KK0000loXWWKodNWWWWOodxokNWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWNK0000000000000klxXWWWWNkdxxxxxxxxokNWWWKlo000O:c0Oc:k00KNWWWWWWWWWWW\n" +
            "WWWWWWWWWNkoxxxxxxxxxxxxxxxONWWWWWWWWWWWWWWWWWWWWWWWKkxxxxddxxxdxkxxdkNWWWWWWWWW\n" +
            "WWWWWWWWW0lkWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWklOWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWWWWWWWNXOkxxxxxkxxxkOKWWWWWWMWWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWO:lkxxxkkkkkkkxxxxkkxxxkkxoddxxddddxddddddddodxxxkxkkxxkkkko:kWWWWWWWWW\n" +
            "WWWWWWWWWOcd00000000000000000000Ol;lxxdxxxkkOOOkxxdxko;lk00000000000d:kWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWWXdokxox00kkxxkKWWWNKxoxOodXWWWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWNdo0do00dodkKNNWWWWWWWKooOooXWWWWWWWWW0lOWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWOlOxlK0lxNWWWWWWWWWWWWWKldOlkWWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWdl0ldNxoXWWWWWWWWWWWWWWWxl0odNWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWdo0ldNXXWWWWWWWWWWWWWWWWxl0ooNWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWOlOxlKWWWWWWWWWWWWWWWWWXldOlkWWWWWWWWW0lOWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWNdoOdoKWWWWWWWWWWWWWWWKooOooXWWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWWXdlkkoxKNWWWWWWWWWNKxoxkodXWWWWWWWWWW0lkWWWWWWWWW\n" +
            "WWWWWWWWWOcd0OO0OOOOOOOO00OO0000kl;lkxddxxkOOOOkxxdxko;ckO0OO000O0O0d:kWWWWWWWWW\n" +
            "WWWWWWWWWO:lkxxkkkkkkkkkkxkkxkkkkxddddxdddddxxdddxxddddxxkkxxxxkkxxkl:kWWWWWWWWW\n" +
            "WWWWWWWWWOlOWWWWWWWWWWWWWWWWWWWWWWWWWX0kxxxxkxxxxkOXWWWWWWWWWWWWWWWW0lOWWWWWWWWW\n" +
            "WWWWWWWWWXdoO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000KKKKKKKKKKKKKKKKKK00OooKWWWWWWWWW\n" +
            "WWWWWWWWWWXOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxxxxxxOXWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n";

    public static String car = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWNKOkxddddooo;':oddddddxk0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWNKkdodddxO0KXXNNK: ,OXXKK0kxddoodOXNWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWNKdc:lx0NWWWWWWWWWWNo .OWWWWWWWWWN0kdddx0NWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWNOc;:xKWWWWWWWWWWWWWWWx..dWWWWWWWWWWWWWNKxoldOXWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWXk:..;looooooooooooooooo:. ,odddddddddddddddo:..';coddkk0KKXNWWWWWWWWW\n" +
            "WWWWNX0kdc'.                                                      ...',:ldkKNWWW\n" +
            "0oc;,..                                                                    .;dXW\n" +
            "'             .''.....'..                                   .''.....'..       :0\n" +
            "            .,'...','...,'                                .,,...','...',.      ;\n" +
            "           ';. ;kKNNX0o. ';.                             .;. ,xKNNNKd' .;.      \n" +
            ":.        .;. :XWWWWWWWx. ,'                             ,' ,0WWWWWWWO' ,,      \n" +
            "X0kxol:;,.,:. lNWWWWWWWO. ,,                             ;' ;KWWWWWWWK; ':.....:\n" +
            "WWWWWWWNNXX0: .dXWWWWN0: .dOxdddddoooooooooooooooooooooodkl .lKWWWWWKc..o00000KN\n" +
            "WWWWWWWWWWWWKc..'cool;..,kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd...:loo:. .dXWWWWWWW\n" +
            "WWWWWWWWWWWWWN0o:,'',;ckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd:,...,cdKNWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKXNWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n";

    public static String bottle ="NXNNNNNXNNXNNXXXNNNNNXNNNNNNNXXNNNNNNNNXXNNXXXXNNNNNNNNNNNNXNNNNXNNNNXNNXNNXNNNN\n" +
            "NXXNNXNNNNNXNNXNNNNNNNNNXXNNXNNNNNNNNNNNNNNNNXNNXNNNNNNNNNXNNNXNNXNNXXNXXNNNNNNN\n" +
            "XNNXNNNXNNNNNXXXNNNXXNNNNNXNNNNNNNX0xxxxxkxx0NNNNNNNNNNNNXNNXNNNNNNNNNXNXNNNNNNN\n" +
            "NXNNXNNNNNNNNNNXNNNNNNNNNNNNNNNNNNKc:ooddoo;cKNNNNNNNNNNNNNNNXNNNNNNNXNNXNNNNNNN\n" +
            "NNNNNNXNNXNNNNNNXXNNXNNXNNXNNXXNNN0clOkkOkOlc0NXNNNNNNNNNXXNNNNXNNNNNNXNNXXNNXNN\n" +
            "NNNXXNNXNNXNNXNXXNNNXNNNNNXNNXXNXNKlxNNXXXNxlKNXNNXNNNXNNNNNNNNXXNNXNNXNNNNNNNNN\n" +
            "NNXNNXNNNNNNNNXXNNNNNXNNXXNNXNNXNWKlxNXNNNNxl0NNNXNNNNNXNNNXNNXNNXNNXNNXXNNXNNNN\n" +
            "NNNXNNNNNNNNNXXNXXNNXNNNNNXNNNNNNN0lkNNNNXNOlONXNNXNNNXNNXNNXNNNNNNNNNXXNXNNNXNN\n" +
            "NNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNWkl0NXNNNN0lxNNNNNNNNNNNNXNNNNNNNNNNNNNXNNNNNNN\n" +
            "NNNNXNNXNNNXNNNNNNNNNNNNNNNXNXXNXNxlKNNNNXNXldNNNNXNNNXNNNNXXNNXXNNNXNNNXXNNNNNN\n" +
            "NNNNNNXNNXNNNXNNNNNNNNNNNNXXNXXNNXooXNNNXNNXooXNNNNXNXNNNXXNXXNXXNXXNXXNNXNNNNNN\n" +
            "NXNNNXNNXNNXXNNXNNXNNXNNNNNNNNNNNXodNNNNNNNNdlKNNNNNXNNNNNXNNNXNNXXNXXNNXNNXNNXN\n" +
            "XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0lkNNNNXNNNxlKNNNXNNNXNNNNNNNNNNNNNNNXNNNNNNNNN\n" +
            "NNNNNXNNNNNNNNNXNNXNNXNNXXNNXNNXNOlkNNXNNNNNOlONNXNNNNNXNNNNNNNNNNNNNNNNXNNNNNXN\n" +
            "XNNXNNXXNXXNNXNNXXNNXNNXNNXNNXXNNdlKNXNXXXNN0lxNNNXNNNXNNXNNXNNXNNXXNXXNNNXNNXNN\n" +
            "XNNNNNXXNNXNNXNNXNNNXNXXNNXNNXXXOlkXNNNNXNNXXklONNNNNXNNNXNNXNNXXNNXNNXNNXNNNXNN\n" +
            "NNNNNNNNNNNNNNNNNNNNNXXNNXNNXNXxoOXXNNNNNNNNNXOlxXNNXNNXNNXNNNNNNNNNNNNNNNNNNNXX\n" +
            "XNNXNNNNNNNNNXNNNXNNXNNNXNNNNNxl0NNNXNNNXNNNNNNOlkNNNNNNNXNNXNNXNNNNNNNNNNNNNNNN\n" +
            "NXNNNXNNNNNNXNNNNNNNNXNNXXNNNXooNNXXNNXNNNXNNXNNdoXNNNNXNNXXNNNNNNNNXXNNXNNNNNNN\n" +
            "NNNNXNNXXXNXNNXNNNNNNXNNXNNNNKlxNXXNXNNXXXNNXXNNdlKNNNXXXNNXNNXXXXNNNXNNNNXXNNXN\n" +
            "NNNNNNNNNXXNNXNNXXNNXNNXNNXNNKlxNXNX0kxxxxk0XNXNxl0NNNXNNNNNXXNNXNNXNNNNNNXNNXNN\n" +
            "NNNNNXNNNNNNXNNXNNNNNNNNNNNNNKlxNXkodxxOOkxdokXNxlKNNNNNNNNNNNNNNNNNNXNNNNNNNNNN\n" +
            "NNNXNNNNNNXNXXNNNNNNNNNNNNNNNKlxXdo0XNNNNNNN0ldXxlKNNXXNNXXNXXNNXNNNNNNNXXNNNNNN\n" +
            "NXNNXNNNNNNXNNNXNNNNNXNNNXNNNKlxkl0NNNNNNNNNN0lkxlKNNNNNNNNXNNNNNNNNNNNNXNNNNNXN\n" +
            "NNXNNXNNNXXNXNNNNXNXXXXNNNNXNKlxxl0NNNNNXXNNNKlxxlKNNXNNNNNNNXNNNNNNNXNNXNNNNNNN\n" +
            "XNNNNNXXNNXNNNNNXNNXXNNXNNNNNKlxKodXNXXXXXNNKooKxlKNNXXNNNNNNNNNXNNXNNXNNXXNNXNN\n" +
            "NNNNNXNNNNNNNNNXNNXXNXXNNNNNNKldNKxoxkO00OkxodKWxlKNXNNXNNNNNNXNNNNNNNNNXNNXNNNN\n" +
            "XNNNNNXXNNNNNNNNNNNNNNXXNNXNNKlxNXNKkxxxxxxkKNXNxlKNNNNNNNNNNNNNNNNNNNXNNNNNNNNN\n" +
            "NNNNNNNNNNNXNNXXNNNNNXNNNXNNNKldNNNXNNNNNNNNNNXNxlKNXNNXNNXXNNNNXNNNNNNNXNNNNNXN\n" +
            "NNNNNXXXNNNXXNNXNNNNNNNNNNNNNKldNNXXNNXNNNNNXNXNdlKNNNNNNNXNNNNXNXNNXXNXNNNNNNNN\n" +
            "NNNNNNNNNNXNNXNNXXNNXNNNNNNNNKlxNXNNNNNNXXNNXNNNdlKNNXXNNNNNNNNNNNNNNNNNNXNNNXNN\n" +
            "NNXNNNNNXNNXNNNXNNXNNXNNNNNNNXodNNNNNXXNNNXNNXNNdlKNXXNNNNNXNNNNNXNNXNNNNNNXNNNN\n" +
            "NNNNNNNNNNNNNNNNNNNNNNNXNNNNNKldNXNNNNNNXNNNNNNNdoKNNNXNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
            "NXXNNXNNNNNNNNXXNNNNNXNNXXNNNXodNNXXNNNNNNNNNNXNdoXNNNNNNNXXNNXNNNNNXNNNNNNNNNXX\n" +
            "NXXNNNNNNNNNXNNNNXNNNXNNXXNXNXdoKNNNNNNNXNNNNNNXodXNXNNNNNXXNNNNNNNNNXNNNNNNNNXN\n" +
            "XNNXNNNNNNNNNNNNXNNNXNNNNNXNNNKxdxxxxxxxxxxdxxxdxKNXNNXNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
            "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKK0000000000000XXNNNXNNNNNXNNNNNNNNNNNNNNNNNNNNN\n" +
            "XNNNNNXNNNNNNNNNXXNNXNNXNNXNNNNNXXNNXNNXXNNNXNNXNNNNNNNNNNNNNNNNNNNNNNXNNNNNNXNN\n" +
            "NXNNNXNNNNNNNNNXNNXNNXXNXXNNXNNXXXXXXXXXXXXXXXXNNXNNXNNXNNXXNNNNNNNNXNNXXNNXNNXX\n";

    public static String shoe = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0OkO000KXWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkdxOO0Okkk000KXNWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNkokK0XWXK00OkxkO00000KKXNWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0ddO0XWWWWWWNXK000OO00KK0OKWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKk00kk0NWWWWWWWWWWNXK0000KOkNWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOkXWWNK0kk0KNWWWWWWWWWWWNX0xxXWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxoxXWWWWW0x0000KNWWWWWWWWWWWXk0WWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xdx0XKXWWWWWOONWWX0O0XWWWWWWWWWW0ONWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOxkO0OkKWWXXXXK0OXWWWWWNKO0NWWWWWWWWKkKWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXKOxxkOxkNMWNK0000000KNWWWWWWWWKkXWWWWWWWWNk0WWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWX0O0koddoloxKNNXKK0OKNWWWWWWWWWWWWWWW0ONWWWWWWWWWOOWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWXK00Ollxkdx0XXKxx0000KXWWWWWWWWWWWWWWWWWXk0WWWWWWWWWW0ONWWWW\n" +
            "WWWWWWWWWWNNNNNXK00000XXOxO0XXWWWWXxkXNWWWWWWWWWWWWWWWWWWWWW0ONWWWWWWWWWWKkXWWWW\n" +
            "WWWWWWN0kkO000000KXNWWWWKk0NWWWWWWKkKWWWWWWWWWWWWWWWWWWWWWWKkKWWWWWWWWWWWKkXWWWW\n" +
            "WWWWWKO0K0000000000000KNWOokXWWWWWXk0WWWWWWWWWWWWWWWWWWWWWKkKWWWWWWWWWWWWKkKWWWW\n" +
            "WWWWNkxXWWWWWNNNNNNNXK0O0kxkOXWWWWW0kXWWWWWWWWWWWWWWWWWWN0k0NNNNXXXXXXKKKOxKWWWW\n" +
            "WWWWKxk0000KKKXXXNNNNNNX0O0XOx0KKKKOddOOOOOOOOOOOOOOOOO0Oxk00000000000000OxKWWWW\n" +
            "WWWWXkKWNXKK00000000000000000OO00000OOO000000KKKXXXNNNNWWWWWWWWWWWWWWWWWWXk0WWWW\n" +
            "WWWWWKO0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk0WWWW\n" +
            "WWWWWWWXK0000000KKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKOONWWWW\n" +
            "WWWWWWWWWWWWNNXKKKK0000000000000000000000000000000000000000000000000000KKXWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n";

    public static String book = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXKKKKKKKXKKKKKKKXWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWNNNNNWWWWWWNXKKKKKKKKKKKKKKKKKKXXKKKKNWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWNXKKKKKKKKKKKKXNK0KXWWWWWWWWWWWWWWWWWWWWWNKK0KNWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWNXKKKKXNWWWWWWWWNXKOkXWWWWWWWWWWWWWWWWWWWWWWWWWWNK00KNWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWNXK0KXNWWWWWWWWWWWWWWWNK0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KKNWWWWWWWWWWWWWW\n" +
            "WWWNK00KXWWWWWWWWWWWWWWWWWWWWWNK0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0KXNWWWWWWWWWWW\n" +
            "WWN0kOXWWWWWWWWWWWWWWWWWWWWWWWWWNK0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK00XWWWWWWWWW\n" +
            "WXkONK0XWWWWWWWWWWWWWWWWWWWWWWWWWWX00XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXK0KXWWWWWW\n" +
            "W0dkXWXOKWWWWWWWWWWWWWWWWWWWWWWWWWWWX0KNWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXK0kxOXWWWW\n" +
            "WN0kkKWN00NWWWWWWWWWWWWWWWWWWWWWWWWWWNK00KWWWWWWWWWWWWWNNXKKKKKKKKKKKKKXXKkOWWWW\n" +
            "MWNKkk0NW00NWWWWWWWWWWWWWWWWWWWWWWWWWWWNK00XWWWWWWWXKKKKKKXXNNWWWWMWWWWWWWOd0NWW\n" +
            "WWWWKOkOXWKOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX00XWWNK0KXNWWWNXKKKKKKKKKKKKKK0OkkOXW\n" +
            "WWWWWXOOOKWXOKWWWWWWWWWWWWWWWWWWXKKKKKKKKKKKOxkOO0NWNKKKK0OOOOO000000000000K0OKW\n" +
            "WWWWWWN0kOKNX00NWWWWWWWWWWWXXKKKKKKXNWWWWWWNKkddOKKK0OO0KKKKXXXNNNWWWWWWWWWWWWWW\n" +
            "WWWWWWWNKOk0NN00XWWWWWWNKKKKKXNWWWWNXKKKKKKK0KXNNXKKKKXNWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWKOOOXWKOXWNKKKKKXWWWWNXKKK0OkkOO00KKKKKKKKXWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWXOOOKWXkOKKXWWWWNXK00OkO0KKKXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWX0OO0X00WWWNXK0OkO0KKXNWWMWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWN0OOOxOXK0Okk0KKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWKOOxdkk0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWX00KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWMWWWMWWMWWWMWWWMWWWMWWWMWWMMWWMMWWMWWWMMWWWMWWMMWWMMWWMWWWMWWWMWWMMWWMMWWMWWWM\n";

    public static String guitar = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0OXWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXOoc'.;oxKNWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKkd:'. .,lxkc:0WW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc...,cx0X0kdclKWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;;d0NWWKocdxOXWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNO:cKWWWW0ccKWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOocxKK00kocdKWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOlcxK0ocoooxKNWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOlcxX0ocdKWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNkllkXKdcdKWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkclkXKdcoKWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxclONKdco0WWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxclONXxco0NWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWXKKXWWWWWWWWWWWKdcoONXxclONWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWXkooolcOWWWWWWWWKdco0NXkclONWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWXxcoOXNd;kWWWWWKkoco0WNkllONWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWW0lcONWWk;dNWWN0occo0WNkllkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWO:lKWWWWx;kWN0ocdKNWNOlckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWNk:dXWWWWWXd:olcdKWNXOlcxXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWNx:xNWWWWWWWNOoxKWN0l:cxXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWKo:kNWWWWWWWWWWWWW0ocdOKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWNX0Odcl0WWWWWNWWWWWWW0ocdKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWNKkdooooox0NWWWWW0lo0NWWXd:oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWN0dllox0XNWWWWWWWXXNX0dco0NXd:o0XX0kxdoxXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWW0ocd0NWWWWWWWWWWWXxco0NWKxxXWN0xooooodkl,kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWNk:oKWWWWWWWWWWWKk0NNKdco0WWWWWWWWWNNXX0d:dXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WW0:lXWWWWWWWWWWWW0o:o0NWKk0NWWWWWWNKkdllld0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWk;xWWWWWWWWWKkONWWKdcdXWWWWWWWWKdllokKNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WW0:oNWWWWWWNx;:clkNWWK0NWWWWWWXd:oONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWNd:kNWWWWWNOlcdd:c0WWWWWWWWWNo:OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWNd:xNWWWWWWNklc:c0WWWWWWWWWO:dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWNk:l0WWWWWWWN00NWWWWWWWWWXlcKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWKdcdKWWWWWWWWWWWWWWWWWNd:kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWW0ocd0NWWWWWWWWWWWWWXd:kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWN0dclkXWWWWWWWWWNOlcONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWXkoloxO0KKKOdllxXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWXOxdooooodONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXNNXNXXXXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n";

    public static String glasses = "MMMWWWWMMWWNWMMMWNNKOxl;'....;lkXMMMWNWWMMMMWNWMMMWWNWMMMWWWWMMMWWWWMMWWNWMMMWWN\n" +
            "MMWWWWWMMWWNNK0koc:,..';ccc:;'.':oOXWWWWMMMWWWWWMMWWWWMMMWWWWMMWWWWWMMWWWWWMMWWW\n" +
            "WWWWMWNKOxl:,'....;cokKNWMWNXKOo;..,lkXWWWWWMMMWWWWMMWWWWWMMWWWWMMMWWWWMMWWWWWMM\n" +
            "WX0kdc;'....,:ldkKNWWWWWWWWWWWWWXk:...:0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "c,....';ldk0XWMMWWWWMMWWWWWMMWWWWMNOc;oXMMMMWWWWMMWWWWMMMWWWWMMWWWWWMMWWWWMMMWWW\n" +
            ".....;o0NWMWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            ".......':oONWWWWWMMWWWWWMMWWWWMMWWWWWMMWWWWWWMWWWWWMMWWWWWMMWWWWMMMWWWWWNXKNWWMM\n" +
            ". .oxl;....,lONWWWWWMMWWWWWMMWWWWMMMWWWWMMMWWWWWMMWWWWMMMWWWWMMWWWWWWKkl;'';dKWW\n" +
            ";..xWWN0xc,...;d0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKko:'..,;;..,xK\n" +
            "o..oWMWWWWXOo;..'l0NWWWWNNXXNWMMMWWWWMMWWWWWMMMWWWWMMWWWWWMMNKko:'..'cxKNNXk,..;\n" +
            "0;.:KWWWWWWWWXx'..':oddl;,,,;codxOKXNNWWMWWWWWWWMMWWWWWWNKko:'...,lkXWWWWWWW0lcx\n" +
            "Nd..xWWMMWWWWMNd........';;;,'.....';:lodxk00KXNNXXK0kdl;....;lx0XWWMMWWWWMMWWNW\n" +
            "WK:.:KWWWWMMWWWO,.......xNNXXXK0Oxdol:;,'....',,,,''.....:okKXNWMMMWWWWMMWWWWWMM\n" +
            "WW0;.:0WWWWWWWWO'.;xk:..dWWWWWWWWWWWWWNXXKOd;........'cxKNWWWWWWWWWWWWWWWWWWWWWW\n" +
            "MMW0c.,dKWWWWMWd..dNMK:.cKWMMWWWWMMMWWWWMMMWK:.....,oKWMMWWWWMMWWWWWMMWWWWMMMWWW\n" +
            "WWWWNOc',cxKNW0;.oXWWNx..xWWWWMMWWWWWMWWWWWWWk....oKWWWWWWMWWWWWMMWWWWWWMWWWWWMM\n" +
            "WWWWMWN0d:',:c;,dXMWWWXl.;0WWWMMWWWWWMMWWWWWWk' .dNMMWWWWWMMWWWWMMMWWWWMMWWWWWMM\n" +
            "MMWWWWWMMN0kddkKNWWWMMM0:.:0WWWWWMMMWWWWMMMWNo..lNWWWWMMMWWWWMMWWWWWMMWWWWMMMWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWW0:.,xXWWWWWWWWWWWWWWK:.:0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWMMMWWWWMMWWWWWMMWWWWMMXd,.;okKXNWWMMWWWNXo.:0NWWMMWWWWWMMWWWWMMMWWWWMMMWWWWMM\n" +
            "MMWWWWWMWWWWWMMWWWWWMMWWWWWNOdc:;;:cloooool;;oKWMMWWWWWMWWWWWMMWWWWWMWWWWWWMWWWW\n" +
            "MMWWWWWMMWWWWMMMWWWWMMWWWWWMMWNXOxc,......'lONWWMMWWWWMMMWWWWMMWWWWMMMWWWWMMMWWN\n";

    public static String dog = "MMMMMMMMWNOkKWWMMMMMMMMMMWMXo,;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMXl. .oXMMMMMMMMMMWO'   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMM0'    lNMMMMMMMMNd.    .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMM0'    .oNMMMMMWO:       dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMWMMMK,     .:ooolc,.        dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMWWWWKo,.                     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMW0c.                        '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMXo.                          :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMk.                          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMK,                          ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MWK,                           .lO0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "WO,                               .,x0KKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "X:                                   ......:loollc:::;;::cox0NWMMMWMWWMMMMMMMMMM\n" +
            "K,                                                          .';:lxXWWMMMMMMMMMMM\n" +
            "Nc                                                                .cONWMMMMMMMMM\n" +
            "WXkooc,.                                                            .;dKWMMMMMMM\n" +
            "MMMMMMW0l,.                                                            .oXMMMMMM\n" +
            "MMMMMMMMMNKOdc'                                                          :KMMMMM\n" +
            "MMMMMMMMMMWMMWNk,                                                         lNMMMM\n" +
            "MMMMMMMMMMMMMMWMO.                                                        .OMMMM\n" +
            "MMMMMMMMMMMMMMMMK,                                                        .xMMMM\n" +
            "MMMMMMMMMMMMMMMMX;                                                         dWMMM\n" +
            "MMMMMMMMMMMMMMMMWl                                                         dMMMM\n" +
            "MMMMMMMMMMMMMMMMWK:                                                        :XMMM\n" +
            "MMMMMMMMMMMMMMMMMWXl.                                ..        .;'         '0MMM\n" +
            "MMMMMMMMMMMMMMMMMMMWk.                           .'cxKk'       .kK:        .dWMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWO.                        ;x0NMMMWO,      .kWNo.       ,KMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMK,                       :NMMMMMMMMKc.     :KMNk,      .OMM\n" +
            "MMMMMMMMMMMMMMMMMMMMM0,      .cc,'..          dMMMMMMMMMMW0;    .xMMMXl.    .cXW\n" +
            "MMMMMMMMMMMMMMMMMMMMMK;      lWMWNNKc        .kMMMMMMMMMMMMO.    dMMMMWO,     oW\n" +
            "MMMMMMMMMMMMMMMMMMMMMWo     .xMMMMMMO.       ,0WMMMMMMMMMWWX;   .xMMMMMMK,    lW\n" +
            "MMMMMMMMMMMMMMMMMMMMMMO.    .OMMMMMMK,       cNMMMMMMMMMMWMX:   .xMMMMMMMd.   ,K\n" +
            "MMMMMMMMMMMMMMMMMMMMMMK;    .kMMMMMMN:      .kMMMMMMMMMMMXd,.   .xMMMMMMM0'    o\n" +
            "MMMMMMMMMMMMMMMMMMMMMMK;    .xMMMMMMN:      lWMMMMMMMMMMM0:.. ..:0MMMMMMWO'    :\n" +
            "MMMMMMMMMMMMMMMMMMMMWWk.    .kMMMMMMX;     .kMMMMMMMMMMMMMNK000KNWMMMMMMX:     c\n" +
            "MMMMMMMMMMMMMMMMMMMW0o.     :XMMMMMM0'     '0MMMMMMMMMMMMMMMMMMMMMMMMMMMW0occldK\n" +
            "MMMMMMMMMMMMMMMMMMMk.      .xMMMMMMNl      :XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMKdc:::coONMMMWkc'       oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWO.        .kMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.     .'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String gitbusters = "MMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOkxddoolllllloodxkO0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMWXKOxoc:;,,,'''',,,,'.....'',;cldk0XWWMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMWN0koc;,,,,,,'''',cxOKK0Od:......'''',;:lx0XWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWX0dc;,,,,,,,,'''',ckXWMMMMMMNx;......'''',,,,cdOXWMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMWKxc;,,,,,,,,,'''''ckXWMMMMMMMMMMNx;......''''',,',cd0NMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMN0o:,,',,,,,,''....;xXWMMMMMMMMMMMMMMXx,. ...'''',,,,',;oONMMMMMMMMMMM\n" +
            "MMMMMMMMN0o;,,,,,,,,''...    ;0WMMMMMMMMMMMMMMMMMXx,   ...'''',',,,;lONMMMMMMMMM\n" +
            "MMMMMMWKd:,,,,,,,,,'..   .    .c0WMMMMMMMMMMMMMMMMMXx,    ..'''',,',,;oKWMMMMMMM\n" +
            "MMMMMNOl,,,,,,,,,,,'.. .:kd,    .c0WMMMMMMMMMMMMMMMMMNx,    ..'''',,,',:kNMMMMMM\n" +
            "MMMMNk:,,,,,,,,,,,,,,''';oOOd,    .c0WWWWWMMMMMMMMMMMMMNx,    ..'''',,,';dXWMMMM\n" +
            "MMMXx:,,,,',,'.'',,,,,,'',;okOd,    .,;;;:lkXMMMMMMMMMMMMXx,    ..'''',,,,oKWMMM\n" +
            "MMXd;,,,,,,'..  .,,,,,,,,,',;ok0d'          ;OWMMMMMMMMMMMMNx,    .''''',,,lKWMM\n" +
            "MNx:,,,,,,'.   ,xOo:,,,,,,,'',;okc           ;KMMMMMMMMMMMMMMNx,   ...''''',oXMM\n" +
            "WOc,,,,,''.  ,xNMWN0d:,,,,,,',',;.           ,0MMMMMMMMMMMMMMMMNx,  ....'''',xNM\n" +
            "Ko,,,,,,'..,xNMMMMMWN0d:,,,,,,,''..          .c0WMMMMMMMMMMMMMMMMNx,......''':0W\n" +
            "k:,,,,,,',lKWMMMMMMMMWN0d:,,,,,,,''.           .cOWMMMMMMMMMMMMMMMMNx;......''oN\n" +
            "l,,,,,,,;o0WMMMMMMMMMMMMN0d:,,,,,,,,'.    .c,    .cOWMMMMMMMMMMMMMMMMNk;......:0\n" +
            ":,,,,,,,:xXWMMMMMMMMMMMMMWN0d:,,,,,,,'... .xOd,    .cOXKXNWMMMMMMMMMMMMNk:....'d\n" +
            ";,,,,,,,ckNMMMMMMMMMMMMMMMMWN0d:,,,,,,,''..;okOd,    ....':xXMMMMMMMMMMMMNk;...c\n" +
            ";,,,,,,,cONMMMMMMMMMMMMMMMMMMWN0d:,,,,,,,,,',;lk0o.         ;KMMMMMMMMMMMMMNd..;\n" +
            ";'',,,,,ckNMMMMMMMMMMMMMMMMMMMMMN0d:,',,,,,,'',;oo'          oWMMMMMMMMMMMMMNc.;\n" +
            ";',,,,,,:kXWMMMMMMMMMMMMMMMMMMMMMWN0o;',,,,,,,'','.         .dWMMMMMMMMMMMMM0;.:\n" +
            ":,,,,,,,;dKWMMMMMMMMMMMMMMMMMMMMMMMM0,..'',',,,,''.        .oXMMMMMMMMMMMMXd,..d\n" +
            "l,',,,,,,ckNWMMMMMMMMMMMMMMMMMMMMMMM0'  ..'',,,,,,,'....':dKWMMMMMMMMMMMXd,...;0\n" +
            "x:,,,,,,';o0WMMMMMMMMMMMMMMMMMMMMMMM0'    'c:,,,,,,,''';lkXWWMMMMMMMMWXd,.....oN\n" +
            "Ko,',,,,,';dKWMMMMMMMMMMMMMMMMMMMMMWO.    ,O0d:,,,,,,'''';lkKNWMMMMW0o,......:OW\n" +
            "WO:,,,,,,'.,oKWMMMMMMMMMMMMMMMMMMW0l.      ,xK0d:,,,',,,'',;lkXWWWKo'......',dNM\n" +
            "MNx;,,,,,,'..;kNMMMMMMMMMMMMMMMMMO'         .lXN0d:,,,,,,,,',;lkOo'......'',oXMM\n" +
            "MWXd;,,,,,,'. .:OWMMMMMMMMMMMMMMWo           ,0MMN0d:,,,,,,,,'''. ....'''',lKWMM\n" +
            "MMMXx;,,,,','.. .cOWMMMMMMMMMMMMWk.          cXMMMWNKd:,,,,,,,''..'''',,,,lKWMMM\n" +
            "MMMMNk:,,,,,,,'.. .cONMMMMMMMMMMMWk;.      .lKMMMMMMMN0d:,,,,,,,,'',,,,,;dXWMMMM\n" +
            "MMMMMNOl,,,,,,,,'.. .cONWMMMMMMMMMMN0xooodkXWMMMMMMMMMWNx,'',,,,,',,,,,:kNMMMMMM\n" +
            "MMMMMMWXx:,,,,,,,,'.. .:xKNWMMMMMMMMMMMMMMMMMMMMMMMMWN0o'..'''''''',,;oKWMMMMMMM\n" +
            "MMMMMMMMW0d:,,,,,,,,''...;lk0KXNWWWWMMMMMMMMMWWWWNXKkl'..''''''',,',lONMMMMMMMMM\n" +
            "MMMMMMMMMMN0d:,,,,,,,,,''.',;clodxOO00KKKKK00Okxdol:,''',,,,,',,,;lONMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMW0xc;,,,',,,,,,,''',,,;;:::::::::;;,,,,,,,,,,,',,,,cd0NMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWXOdc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cdOXWMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMWX0xo:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:lx0XWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWWX0kdlc:;,,,,,,,,,,,,,,,,,,,;:cldk0XNWMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMWWNXOxolc;;,,,,,,,,,;;:loxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMM\n";


    public static String pistol = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMWX00XWWWWWWWWWWWWWWWWWMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWNNMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMKxdodooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddkNMMMMMMMMMM\n" +
            "MMMMMMMMMMWdc0WWWNNNNNNNNNNNNNNNNNNNXXXXXXXXXNNNNNNNNNNNNNNNNNNNWWWOcxWMMMMMMMMM\n" +
            "MMMMMMMMMMWdlXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWolNMMMMMMMMM\n" +
            "MMMMMMMMMMWolNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXloNMMMMMMMMM\n" +
            "MMMMMMMMMMNocOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0cxMMMMMMMMMM\n" +
            "MMMMMMMMMMWKkxxxxd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcOMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMNolXMMMMMMMMMMMMMMMMMMN0Okkkk0NMWX0000OOOkkkkxkkxxxoxNMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMWdlNMMMMMMMMMMMMMWXNWWx:odkkkldXkldxxkkkkkkkOOOOO0XNWMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMKlxWMMMMMMMMMMMMMXl,oK0olo0WWkcOdlNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMNdlXMMMMMMMMMMMMMMWOc;ck0OocdxdkNkc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWkcOMMMMMMMMMMMMMXkxxkkkkkkkxxkkOOdcOMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMWklkWMMMMMMMMMMMMKoo00kxxxxxxkkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMXdl0WMMMMMMMMMMMMWxcKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMWKodXMMMMMMMMMMMMMNklxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMWOlxNMMMMMMMMMMMMMWxc0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMOlkWMMMMMMMMMMMMMWKloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMKlxWMMMMMMMMMMMMMM0ldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMWxlKMMMMMMMMMMMMMMXloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMOlxXWMMMMMMMMMMMM0ckMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMWKkddONNNNNNNNNNKolXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMWOdxxxxxxxxxxdxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String git = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl:,............,:lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMWKx:'....................':xKWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWKo,..........................,oKWMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMNx,...'cc;'..............';cc'...,xNMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMXl.....oNWNKxoodxxxxxxdooxKNMNo.....lXMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMXl......dWMMMMMMMMMMMMMMMMMMMMWo......lXMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMWd......'xWMMMMMMMMMMMMMMMMMMMMWx'......dWMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMM0;.....'xWMMMMMMMMMMMMMMMMMMMMMMWx'.....;KMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMk'.....:KMMMMMMMMMMMMMMMMMMMMMMMMK:.....'kMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMx......cXMMMMMMMMMMMMMMMMMMMMMMMMX:......kMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMk'.....,OMMMMMMMMMMMMMMMMMMMMMMMMO,.....'kMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMM0;......cXMMMMMMMMMMMMMMMMMMMMMMXc......;KMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMWd.......:kXMMMMMMMMMMMMMMMMMMXk;.......dWMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMXl...co:'.;ldk0XMMMMMMMMX0kdl;........lXMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMXl..,oOx;....:0MMMMMMMM0;...........lXMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMNx,..:OKkood0WMMMMMMMMWo.........,xNMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWKo,.,lxkkkKWMMMMMMMMWo.......,oKWMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMWKx:'....dWMMMMMMMMWo....':xXWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxo:;kWMMMMMMMMWk;:oxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String gitlab = "MMMMMMMMMMMMMMMMMMMMMMMXxxXWMMMMMMMMMMMMMMMMMMMMMMMMWXxxXMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMWkcckWMMMMMMMMMMMMMMMMMMMMMMMMNkcckWMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWW0l:cl0WMMMMMMMMMMMMMMMMMMMMMMW0lccl0WWWMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMXd:cc:dXWMMMMMMMMMMMMMMMMMMMMMXd:cccdXMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWkcccc:ckWMMMMMMMMMMMMMMMMMMMMWkcccccckWMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMWKo:cc:c:lKWMMMMMMMMMMMMMMMMMMW0l:cccc:oKWMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMWMXdccc::c::dXMMMMMMMMMMMMMMMMMMXd::cc:cccdXMWMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMWOcccccccc:cOWMMMMMMMMMMMMMMMMNOl:ccc::cccOWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMXxlllllolllloxxxxxxxxxxxxxxxxxxollllllllllxXMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMWN0kxdooooooooolc::cc::cc:::c::clooooooooodxk0NMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMWXkkkxddoooooooolc:cc:cccc:cc:clooooooooddxkkkXWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMNOkkkkkxdoooooooocc:cc::::cc:ccoooooooodxkkkkkONMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMWKkkkkkkkkxdoooooolccccc:::c::cloooooodxkkkkkkkkKWMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMNK0Okkkkkkxdodoooolc:cc::cc:cloooododxkkkkkkk0KNMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMWNKOkkkkkkxdoooooc:cc::ccccloooodxkkkkkkOKNWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMWXKOkkkkxddooolcccccc:clodoodxkkkkOKXWMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWNX0Okkkxdooolc:cccclooodxkkkO0XNWMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kkkdoooc:::ccooddxkk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kxdolcccclodxk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc::coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0dlld0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String turtle = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:;:oxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l::::;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0c:llolccOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoloddolcoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWMWNNXXNWMMMMWNd:cooolc:kWMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMWWNKOxdolllox0XWWWWk:lllllc:oKWMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMWN0xol:;;:::c:coodOXWNkccc::;::;lkKNWMWNKkxddxxkKNWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMWNOoc:;::::;;,,:cloolodl::clllllcc:::ldOKOdllcclc:cox0WMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMW0o:::;,;;;:cllokdccccllllodxkkkxooolcc::looolcccc;::;:oONWWMMMMMMMMMM\n" +
            "MMMMMMMMWXkl:;,,:odxOKWWNKxlldkkkkxkkkkkxkkddxxoollc::::::;;;;::;:co0NMMMMMMMMMM\n" +
            "MMMMMMMWOlloxxx0XWMMMMMNk:cx00000000OxkOOOOxxkOxooolll:;oOxo:::clcclldXMMMMMMMMM\n" +
            "MMMMMMMXxkNWMMMMMMMMMMNd:lkOO00KKXKOkk0KKKK0OO00koloooo:;oKWNKkol:lol:oKMMMMMMMM\n" +
            "MMMMMMMWNMMMMMMMMMMMMWOc:okkOO00O00Ok0KKKKX0OO0K0Odoooolc:oKWMWN0xolcccdXMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMXocldxkOO00000OOO00KKK0O0KK0kolc::::c;lKMMMMWWKdlcc0MMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMO::dkO00KKKKXK0OkkOOO0OkO00kxdool:;cc;,oNMMWWWWWXdcOMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMO::oOKXXKKKKK00OxdxxxkxxkkkxO0Oxo:cloc;c0MMMMWMMMN0XMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMM0:,ck0KK00000OkxxxkkOOkO00xxkOOkxoodol::OMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMNo',lxxxxxxxxkxxxkOO00OOKKOddxxxdoodoc;;kMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMWOc;:lccodxkkOOkkkkkOOkk0KOxddoodoodl:,;OMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMWx,,:clxOO00KK0Okddxxxxkkxdollllccloc'cXMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMXd:;:dkO0KKK0OOkkkkxxxxxdoollcc:::;';OWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMNOl,;okO0OkxkOO000OOkdoooollllc:,''dNMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMW0c';odoloddxkOOkxkxollloooll:;';xNMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMWKl,,;:ldxxdddddollccloll:;,,:xXWMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMWKl,''',:looxkkkdoloool:;;;lxKWMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMNkl:;;;,,;,',:clc::;;;''';oKNWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMXxc;;;;;,;xOoc,''....,,,;;oXWWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMKo:;;;;;,;kNWWNkc;ld;';::;,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMWKl;c:,,;;cOWMMMMNXKNXl':ccc::OMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMXxoloodOKNMMMMMMMMWMWOc;cc::;kMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMWNWMMMWWMMMMMMMMMMMWNOdc;;;kWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdkXMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String pikachu = "MMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMM\n" +
            "MMMM0cckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:dNMM\n" +
            "MMMMx. .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.  cNMM\n" +
            "MMMMk.   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'    dWMM\n" +
            "MMMMK,    .:xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l:.   .kMMM\n" +
            "MMMMNl   .xOolOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcx0c   ,KMMM\n" +
            "MMMMMk.  :0XKxcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNklo0XXd.  cNMMM\n" +
            "MMMMMNc .oXXXX0olOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0olkKXXXO' .dWMMM\n" +
            "MMMMMMO'.dXXXXXKkcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxcdKXXXXX0: ,0MMMM\n" +
            "MMMMMMWo'dXXXXXXX0ocOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOllOXXXXXXXKc.dWMMMM\n" +
            "MMMMMMMXoc0XXXXXXXKxcxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxcxKXXXXXXXX0ccXMMMMM\n" +
            "MMMMMMMMXll0XXXXXXXXOloKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXolOXXXXXXXXXKdcOWMMMMM\n" +
            "MMMMMMMMMXol0XXXXXXXX0olOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lo0XXXXXXXXXKdckWMMMMMM\n" +
            "MMMMMMMMMMXolOXXXXXXXXKxckWMMWNXK0OkkxxxxxxxkkO00KNWMMWOldKXXXXXXXXX0ocOWMMMMMMM\n" +
            "MMMMMMMMMMMNdckXXXXXXXXXklokxxxddddxxxxxkkxxxddddddxxkdlkXXXXXXXXXKkloKMMMMMMMMM\n" +
            "MMMMMMMMMMMMWkcd0XXXXXXXXkodOKXXXXXXXXXXXXXXXXXXXXXK0dlkXXXXXXXXXOolkNMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMWKolkKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00XXXXXXXKkolxXMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMW0ookKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkc:xXMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMKook0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0xcoXMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMXloKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOcoNMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWxcOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxc0MMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMXllKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOcxWMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMM0cdXXXXXK0OO0XXXXXXXXXXXXXXXXXXXXXXXXXXXKOkk0KXXXXKloWMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMM0cxXXX0o,..,;cxKXXXXXXXXXXXXXXXXXXXXXX0dc:'..;xKXXKloNMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMM0cxXX0:  .oKO,.oKXXXXXXXXXXXXXXXXXXXX0c.oX0,  .oKXKllNMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMM0cxXXx.   ;oc. ;0XXXXXXXXXXXXXXXXXXXXk' 'ol.   ;0XKllNMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMOcxXXO,       .oKXXXXXXXXXXXXXXXXXXXX0:        lKXKolXMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMk:d0KXOc.   .'oKXXXXXXXXXXXXXXXXXXXXXXOc.    .l0K0OlcKMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMx';clokK0kdxkKXXXXXXXXXXOoclkKXXXXXXXXXK0xddk00dlc:';0MMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMx';::;:lOXXXXXXXXXXXXXXXKkxx0XXXXXXXXXXXXXXXKk:;;::,,OMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMx';::::;cOXXXXX0OOKXXXXXKOkkOKXXXXK0kOKXXXXXx;;::::,,OMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMk,,:::::;oKXXXXKOxxxxxxxxxxkxxkkkkxxk0XXXXX0c,:::::';0MMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMXc';::::;:OXXXXXXXK0OO0KKXXXXXKK0KKXXXXXXXXk:,::::;'lNMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMM0;';:::;c0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0c,:::;'cKMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMKl',;:lOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOl:;',dXMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMNOc;lOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOl,l0WMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMW0dooxOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0xood0NWWWWWWWWNNWWWWWWW\n" +
            "MMMMMMMMMMMMMMMMMMMMMMNOxdoodxOKKXXXXXXXXXXXXXXXXXK0OxdodxONWKxxk00OOkkxkOK0OkxO\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMWNKkxdddddddddddddddddddddddxOXWMMMMX0O0KXK000OO0KKK00K\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OkxxxxxkkkOO00KXNWMMMMMMMMMMMMMMMMMMMWWWMMMMMM\n";

    public static String batman = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWNXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWOkXWWWWWWWWWWWWWWWOdKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWNd:0WWWWWWWWWWWWWWKc,OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWXl.oNWWWWWWWWWWWWXo.'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWK:.,OX0OxdddddxkOo. .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWO, .',............. .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWk'...................dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWx....................lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWx....................:KWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWk'...................:KWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWK:...................lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWNo..,ldl;.....:odc'..xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWx....,,......';,...'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWx..,,...........,;.'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWNl..o0kxolcclldxO0x'.kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWK:..c0XKKKKKKKKKXKo..dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWO,..;OXKK00000KKXO;..oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWNd....oKXXKXKKXXX0l...:KWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWNKOdc'.....;okO000Oxl,.....cxOKNWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWNKko:'............'''''...........':ldOXNWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWNOc'.....................................,cdKWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWKxc'.....................................'lKWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWNKxl;..............................,cokKNWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWX0ko:,..................',:cok0XNWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kdlc;,,,,,;:lodkOKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKKKKXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n";

    public static String windows = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdlc:,'...........',:coxOKNMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOoc,..                         .,cdOX\n" +
            "0xONMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;cl.                                   :\n" +
            ";'oNMNOo:oXMMMMWNWMMMMWNNWMMMNKkOKx:.    .:.         ..     ,ccc::;'.          ,\n" +
            "KXWMM0;.,dNW0xl;cKNKko:'lK0oc,. ;l.      .:.   .,:oxO00:   .xMMMMMWNX0xl'      ,\n" +
            "MMMMMNKKNMM0,  .cKx.    :k'     ,l.      .ollx0XWMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "0dOWMMMMMMMXddOXWWo..,cd0O.   .;xo. ..''':0WMMMMMMMMMMNc   .xMMMMMMMMMMWo      '\n" +
            "l:OWMMKdlkWMMMMMWWKOKWWWWKolx0KXNO;''..  .kMMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "WWMMMWd';kWMXko:dNWXOdc;kWNOdl;'dx.      .kMMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "MMMMMMNXWMMWo..'dNXc   .dWx.    ld.      ,0MMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "OoOWMMMMMMMW0k0NWMXc':okXWo. .;l0x...'''':0MMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "ocOWMMKdcxWMMMMWWMWNNWWWWMKxOKK0KO:''.   .kMMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "WWMMMWx,;kWMXkl:dNWXko:;kWXxc;..ox.      .kMMMMMMWNK0kd'    ,ccllodxk0KXo      ,\n" +
            "MMMMMMNNWMMWo..'dNX:   .dWd.    od.     .,0WN0koc;'.                  .'.      '\n" +
            "klxNMMMMWWWWKOKNWMXc':oONWd..;lxKx...'''':dl'.              .......            '\n" +
            ":;kWMNkl;lXMMMMNNWWNNWWXXWX0KX0xkx;'..   .:.    .,:loxx;   .dNNXXK0Oxoc,.      ,\n" +
            "NWMMM0;.;xNNOo:,:KNOdc,.cKkl;.. ,l.      .c;,cdOXNWMMMNc   .xMMMMMMMMMMNl      ,\n" +
            "MMMMMWXNWMM0' ..lKd.    cx'     ,l.    ..;OXNMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "OoOWMMMMWWMXxx0NWWo..;lxKO.  .':kx'.''''':0MMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "ol0WMWKo:xWMMMMWWWXKNWWNWKdokKKKXO:'.    .kMMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "WMMMMWx,:OWWXxl;oNWKxl:,xWXko:'.od.      .kMMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "MMMMMMNNWMMWo..,xNX:   .dWd.    ld.    ..;0MMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "OoOWMMMMWWMWKOKWMMXl,cdONWd..':o0k'.''''':0MMMMMMMMMMMNc   .xMMMMMMMMMMWo      ,\n" +
            "ol0WMMKocxWMMMWNNWWNNWNXNMKOKXKOKO;..    .kMMMMMMMMMMMXc   .oKKKKXNNWMMWo      ,\n" +
            "WMMMMWx,:OWM0o:'lNW0o:'.xWXxc,..od.      .kMMWNKOxdlc;,.     ......',;cl,      ,\n" +
            "MWWMMMNNWMMWo.':kWX;   .xWd.    od.   ...:kxl;'.                               ,\n" +
            "xcdNMMMMWNWMXKNWMMXo:okKWWd..;lxKk,.''''.;c.                                   ,\n" +
            "c:kWMNkl;lXMMMWKKNMWWWX0KWX00Oxlxx;..    .:.          ...',,;;;;;,''..         ,\n" +
            "WWMMM0;.;xNNxc,.;0Xxl;..:0d:'.  ,l.      .:. ..,:coxk0KXNNWWWWWWWWWNXK0kdl;..  '\n" +
            "MMMMMWXXWMMO' .;dXo    .lx.     ;l.    ..:kkk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMWN0d:l\n" +
            "MMMMMMMMMMMNOOXWMWd';lx0NO. .':oOx'':dOKNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00\n" +
            "MMMMMMMMMMMMMMMMMWXXWMMMM0llkXWMMX0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXX\n";

    public static String java = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:.kMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.'0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc. 'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxo;. .lKMMMMMWXKKNWMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l'   .l0WMMWKxoldkKWMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.  ,cdKWMNOl,';d0WMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,  .:kNMMWKo'..lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;   ,kWMMMNx' .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   cXMMMNKo. .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   ;KMMMMk:.  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  cNMMMMx,.   cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. ,KMMMMKx;    ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx..cXMMMWW0,    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.:KWMMMMKc.   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc:kWMMMMWx.  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdONMMMMN: .dNMMMMMMMMMMWWWWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMWNX000KXWMMMMMMWXNMMMW0::OWMMMMMMMMMN0OxoccdKWMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMN0xl:coxk0XNMMMMMMMMMMMMMN0KWMMMMMWWNNWMWWWWXk; .oXMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMW0:.   ;xO0KKXXXXXXXKKK000OkkxdoolllldOXWMMMMMMMK, .dWMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMNOdlc:;;;;::::::::::;;;;;:::cclodkOKNWMMMMMMMMMK, .dWMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWWNXXXXXXXXXXXNNNNNWWWMMMMMMMMMMMMMMMMMMKc .lXMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMNkcoKMMMMMMMMMMMMMMMMMMWWNXXWMMMMMMMMWKo'.:OWMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMO'  ':clloodddddooollc:;,'..:kNMMMWXkoccdKWMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWKxlc;,..............',;:codkKNMMWKOk0XWMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXKKKKKKKKKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMNOlo0WWMMMMMMMMMMMWWNNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMK:  .,;::cclllccc:;,'...;o0WMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMWXKKKXWMWXxl;'..           ...,:ld0WMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMWXkoloxkO0XWMMMMMWNXKOOkxxxxkkkO0KNWMMMMMMMMMMMMMMMXOXMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMM0c.  'xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kxdxXMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMWO:..  ..,:clodxxkkOO000000000000OOOkkxxdoollllooddk0XWNK0NMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMWXKOkxdolcc:;;,,,,,,,,,,,,,,,,,;;;::cclodxkOKXXXKOxolod0WMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMWNK00OOOOOOOO00000000KKKK0000OkxdoollccccldOXWMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMWXK0OOkkkkkxxxxxxdddddddooooooodxkO0KXNWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String html = "MMMMMMMMMMMMMMMWX0OKNMWX0OKWMMMN0O0NMMMWNKO0XWMMMX0O0NNKOOOOOO0XWMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMWX00000000000000000000000000000000000000000000000000000000XWMMMMMMMMMM\n" +
            "MMMMMMMMMMNklcccccccccccccccccccccccccccccccccccccccccccccccccccccclkNMMMMMMMMMM\n" +
            "MMMMMMMMMMWOlccccccccccccccccccccccccccccccclccccccccccccccccclcccclOWMMMMMMMMMM\n" +
            "MMMMMMMMMMW0lcccccccccccccccccccccccccclllllooolllllllllloollollcccl0WMMMMMMMMMM\n" +
            "MMMMMMMMMMMKocccccccccccccccccccccccccclooooooooooooooooooooooolcccoKMMMMMMMMMMM\n" +
            "MMMMMMMMMMMXdccccccccccccccccccccccccccloooooooooooooooooooooollcccdXMMMMMMMMMMM\n" +
            "MMMMMMMMMMMNxccccccccoxkkkkkkkkkkkkkkkkOOO00O00000000000OOdooollcccxNMMMMMMMMMMM\n" +
            "MMMMMMMMMMMNklcccccccdKNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMWXkooolccclkNMMMMMMMMMMM\n" +
            "MMMMMMMMMMMWOlccccccco0NNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMKxooolccclOWMMMMMMMMMMM\n" +
            "MMMMMMMMMMMW0occccccco0NNNNNNNXXXXXXXXXNNNNNNNNNNNNNWWWNN0dooolccco0WMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMKdccccccclONNNNNN0doooooooodxxxxxxxxxxxxxxxxxdoooolcccdKMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMXxccccccclkXNNNNNOlcccccccclooooooooooooooooooooollcccxXMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMNkccccccccxXNNNNN0occcccccclooooooooooooooooooooollccckNMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMWOlcccccccdKNNNNNXkxxxxxxxxkkkkkkkkkkkkkkkkkxoooolccclOWMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMW0lccccccco0NNNNNNNNNNNNNNNWWWMMMMMMMMMMWWWWKdooolcccl0WMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMKoccccccclONNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMW0dooolcccoKMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMXdccccccclkXNNNNNNNNNNNNNNWWWWWWWWWWMMMMMMWOoooolcccdXMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMNxccccccccodddddddddddddddxkkkkkkkkONMMMMMNOooollcccxNMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMNkccccccccllooooollccccccclooooooooxXMMMMMNkooollccckNMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMWOlcccccccoOKKKKK0dccccccclooooooookNMMMMMXxooolccclOWMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMW0occccccco0NNNNNXxccccccclooooooooOWMMMMWKdooolccco0WMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMKdccccccclONNNNNNOolcccccllooooodxKWMMMMW0oooolcccoKWMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMXdccccccclkXNNNNNNXK0OkxddxkO00KXNWMMMMMNOoooolcccdXMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMNxccccccccxXNNNNNNNNNNNNNNWWWMMMMMMMMMMMNkooollccckNMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWklcccccccok0KXNNNNNNNNNNWMMMMMMMMMMWNNXOdooolccclOWMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMWOlcccccccccloodxkO0KXNNNWMMWWNNXK0OkxdoooooolccclOWMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMM0occccccccccccccccllodxkO0OOkxdooooooooooooolccco0MMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMKdcccccccccccccccccccccclooooooooooooooooolllcccdKMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMXxccccccccccccccccccccccloooooooooolllllllccccccxXMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMW0xdollccccccccccccccccclloollllllcccccccccllodk0WMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMWWNXK0OkdoolcccccccccccclccccccccclodxkO0KXNWWMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMWWNXK0OkxdolcccccccclodxkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOkdlllldkOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String facebook = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMWKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWMMMMMMMM\n" +
            "MMMMMMMK:.                                                            .:KMMMMMMM\n" +
            "MMMMMMWo                                                                oWMMMMMM\n" +
            "MMMMMMWl                                                                lWMMMMMM\n" +
            "MMMMMMWl                                                                lWMMMMMM\n" +
            "MMMMMMWl                                          .,;:cccc::;,.         lWMMMMMM\n" +
            "MMMMMMWl                                      .;dOXWWMMMMMMMWNl         lWMMMMMM\n" +
            "MMMMMMWl                                    .:0WMMMMMMMMMMMMMWo         lWMMMMMM\n" +
            "MMMMMMWl                                   .dNMMMMMMMMMMMMMMMWo         lWMMMMMM\n" +
            "MMMMMMWl                                   oNMMMMMMMMMMWNXXXXXl         lWMMMMMM\n" +
            "MMMMMMWl                                  '0MMMMMMMMWOc,.......         lWMMMMMM\n" +
            "MMMMMMWl                                  ;XMMMMMMMMO.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                         'cclllcclkWMMMMMMMM0olllllll:.         lWMMMMMM\n" +
            "MMMMMMWl                         oWMMMMMMMMMMMMMMMMMMMMMMMMMM0'         lWMMMMMM\n" +
            "MMMMMMWl                         oWMMMMMMMMMMMMMMMMMMMMMMMMMMx.         lWMMMMMM\n" +
            "MMMMMMWl                         dWMMMMMMMMMMMMMMMMMMMMMMMMMWl          lWMMMMMM\n" +
            "MMMMMMWl                         oWMMMMMMMMMMMMMMMMMMMMMMMMMX;          lWMMMMMM\n" +
            "MMMMMMWl                         .:::::::cxWMMMMMMMM0l::::::,.          lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMWd.                  lWMMMMMM\n" +
            "MMMMMMWl                                  :XMMMMMMMMd.                  lWMMMMMM\n" +
            "MMMMMMWx.                                 :XMMMMMMMWd.                 .xWMMMMMM\n" +
            "MMMMMMMWOl;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;dNMMMMMMMMO:,,,,,,,,,,,,,,;;lOWMMMMMMM\n" +
            "MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMWWWWWWWWWWWWWWWWWMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";


    public static String apple = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc,..   lNMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.   .'.  ;XMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo.  .:dOXO'  cNMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxc'  ,dKWMMWo  .xMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.  .oXMMMMWk.  cNMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.  .dWMMMMNx.  cXMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  .lNMMMNO:. .oXMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  .cONKko,. .;OWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMWX0xolcc:ccldk0XWX:  ..''.   .':oolcc:ccldkKNWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMNOo;.    .....   ..,;.           .   ......   .':dKWMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMWKo,.  ':oxOKKKK0Oxoc,..          .':lxk0KKXK0Oxl;.  .;xXMMMMMMMMMMM\n" +
            "MMMMMMMMMMWKl.  'lOXWMMMMMMMMMMMMWX0kdllcllodkKNWMMMMMMMMMMMMWKx:.  'dXMMMMMMMMM\n" +
            "MMMMMMMMMNd.  ,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:   ;KMMMMMMMM\n" +
            "MMMMMMMMKc  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l.  'oXMMMMMMMM\n" +
            "MMMMMMMK:  ,0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo. .:kNMMMMMMMMMM\n" +
            "MMMMMMNc  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  ;OWMMMMMMMMMMMM\n" +
            "MMMMMMx. .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  lXMMMMMMMMMMMMMM\n" +
            "MMMMMNc  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  :XMMMMMMMMMMMMMMM\n" +
            "MMMMM0'  dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. .kMMMMMMMMMMMMMMMM\n" +
            "MMMMMO. .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd. ,0MMMMMMMMMMMMMMMM\n" +
            "MMMMMk. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. '0MMMMMMMMMMMMMMMM\n" +
            "MMMMMO. .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. .xWMMMMMMMMMMMMMMM\n" +
            "MMMMMK,  oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc  ;KMMMMMMMMMMMMMMM\n" +
            "MMMMMNc  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  :KMMMMMMMMMMMMMM\n" +
            "MMMMMMx. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:  'kNMMMMMMMMMMMM\n" +
            "MMMMMMX;  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo. .;xXWMMMMMMMMM\n" +
            "MMMMMMWk. .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'  .:d0NMMMMMM\n" +
            "MMMMMMMNl  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc.  .OMMMMMM\n" +
            "MMMMMMMMK:  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'  cXMMMMMM\n" +
            "MMMMMMMMM0,  :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,  :XMMMMMMM\n" +
            "MMMMMMMMMM0,  :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'  cXMMMMMMMM\n" +
            "MMMMMMMMMMMK;  ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd. .lXMMMMMMMMM\n" +
            "MMMMMMMMMMMMXc. .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc. .xNMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMNd.  :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'  ;0WMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMW0:  .oKWMMMMMMMMMMMMMWNXXKKKXNWWMMMMMMMMMMMMWO:. .oXMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMNx,  .lONWMMMMWN0xl:,'.......,:lx0NMMMMMWKx;. .:0WMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMXx;.  ':lllc;'.  ..,::cc::,'.  .':lllc;.  .cOWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMN0o:'..  ..':okKNWMMMMMMWNKkl;'..  ..,cxKWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWNK0O00KNWMMMMMMMMMMMMMMMMWNK00O0XNMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";

    public static String pringles = "MMMWWWMMMWWWWMMMWWWWMMMWWWMMMWWWWMMMWWN0xdl:;;oKMMWWWWMMMWWWWMMMWWWWMMWWWWMMMWWW\n" +
            "MMWWWWWMMWWWWMMWWWWWXOxddddxk0XNWWMMNOoloc::ccldkOKNWWMMWWWWWMMMWWWWMMWWWWWMWWWW\n" +
            "WWWMMMWWWWMMMWWWWW0ollllooooodddxOXNk;lxl::dkxxxdddxOXWWWWMMWWWWMMMWWWWMMWWWWMMM\n" +
            "WWWWWWWWWWWWWWN0xocoOOkxxxkkOOkxdolc';xl'cdddxO0XNWKkdxkxxXWWWWWWWWWWWWWWWWWWWWW\n" +
            "MMMWWWMMMWWWNOlcdkKWMMWNXKOxdoc:lol::lolloolodddddddxOOxldXWWMMWWWWWMMWWWWMMMWWW\n" +
            "WWWWMWWWWWWWk:o0KNMWWXOxdooooxO0KXXNWWWWWWWWWWNXXK0kxdo::dKNWWWWWWWWWWWMMWWWWWMM\n" +
            "WWWWMMWWWWMNoc0kOX0doooxOXNNWWMMWWWWWMMWWWWWWKddOXWMMWNKOdlox0NWWMMWWWWMMWWWWWMM\n" +
            "MMMWWWMMMWNk:cOkcclx0NWWWW0llxKWWMMMWWWWMMMMWx'';kWWWWMMMWNOoco0NWWWMMWWWWMMMWWW\n" +
            "WWWWWWWWWW0cc::dclKWWWWWWNl.;;dNWWWWWWWWWWWWWXd;:OWWWWWWWWNXNKd:oKWWWWWWWWWWWWWW\n" +
            "WWWMMMWWWNd',lkOkdkNWWWMMWO;.'dWMWWWMMMWWWWWMMWXKXNNWWNNWW0oxXNOc:OWWWWMMMWWWWMM\n" +
            "WWWWWWWW0c,c0WMMWNNWWMWWWWWXOO00OkkOOKNWMMMWN0doodddddddxxxxoxXWK:;OWMWWWWWMWWWW\n" +
            "MMWWWWXd,;kNWWMMWWWWWMWWWWXkoc::cccccccox0NNx:lOKK0000KKKK0kdlkWWO,:KMWWWWWMWWWW\n" +
            "WWWMMKc.cKMNOONWWMMWWWWNOl::oOKNX0OkOOko:;ld;ckolllloooddxxOkcoXMNo'dNWMMMWWWWMM\n" +
            "WWWW0:.oXWXxcdXWWWWWN0d::o0NWXkl::cclloddl,..;ldOKNNNNNNNNKxocoXWWx'lNWWWWWWWWWW\n" +
            "MMMK:.lNMNdlkdoxxxdocclkXWNOo;:oOXWWX0xolc'..'ldollodxxxdooxxcxWWWx.lNWWWWMMMWWW\n" +
            "WWNo.;0WWKc;OXOxddxk0XWN0dc;lONWWXOocclddo,..'oKX0Oxddddx0XOcoXWWNo.dNWWMWWWWWMM\n" +
            "WWO,.dNWW0::ddkOKKK0kdolclkKWWWXx:;lOXWWW0;'dx;:dOKNNNXKOxlcxXWWWO,;0WWMMWWWWWMM\n" +
            "MMx.'kMMMXc:O0kxddoodxk0XWMMNOl;:xXWWWW0x:.oXNKxl:::::::cokXWMMW0:'xWMWWWWMMMWWW\n" +
            "WWd.'OWWWWk,;xKNWWWWWMWWNKkoccoONWWWWNx,.'oXWWWWWNK000KXNWWWWWWO;,xNWWWWWWWWWWWW\n" +
            "WWx..dNWWWNx',lddxxxdddoooox0NMMMWNKk:';lkNWMMMWWWWMMWWWWMMMWKo,:OWWWWWMMMWWWMMM\n" +
            "MMK:.:KMMWWNOc:ldkkkOO0KXNWMMWNK0xc,,cxXWMMWWWWWMMWWWWMWWWWKd;;dXWWWMMWWWWWMWWWW\n" +
            "MMWk'.lXMWWWWNOocclodxxxxxdolc:;;:lxKNWWMMMWWWWWWXkx0WMWXOl;:xXWWWWWMMWWWWMMMWWW\n" +
            "WWWNx'.c0WMMWWWWNKOxolllllllodk0XNNWMMMWWWWWMWXkc;'.:Okl::oONWWWMMMWWWWMMMWWWMMM\n" +
            "WWWWWO:.'oKWWWWWWWWWWWWWWWXkoodxO0XNWWWWWWWXkl::o0x'.....;lONWWWWWWWWWWWWWWWWWWW\n" +
            "MMWWWWNkc''lkXWMWWWWMMMWWW0,.,llllooddkOOkoccd0NMMO'..,ox:.;0MMWWWWMMMWWWWMMMWWW\n" +
            "WWWWMWWWN0d:,;cok0XNWWWWWMK:.cXMWNXK0OkxdodONWMWWW0, .xNNo.;0WWWWWWWWWWWNWWWWWWM\n" +
            "WWWWMWWWWWWNKOdl:::ccloddxd,.;KMWWWWWNOo:;,;:loxk0x,.'kWNl.,ooc::cd00dc:;:lx0WWM\n" +
            "MMMWWWMMMWWWWMMWNX00Okxdol:'.,OWWMWXx:,cddl'.....';..,0MNc....:lol;'...;cl:''l0W\n" +
            "WWWWWWWWWWWWWWWWWWWWNXKOo;;,.'OWWKo,..o00d'.'coodOKd.;KWK:..:ONWWWXl.,kNWNXd.,OW\n" +
            "WWWMMMWWWWMMMWWWWMM0c,,,;oOKc.lxc'...''''..cKWNXNWWd.:KW0;.cKWKodNMk,oNWO:,'.oNM\n" +
            "WMWWWWWWWNXXXNWMWWWKc.,xXWWO;..':;,o00o. .cXWKc;OMNo.lNM0,'kWNo.;KWO,lXWx..;oKWW\n" +
            "MMWWWX0dl;,',;lONWWWK:.,ldo;..c0NOOWWWK:.'kWNo.'kWNl.oNMO':KMKc,dXWk..xNXc.lXWWW\n" +
            "WWN0o;..,lddo;..oXNKx;..'lko..xWWNKKNMNl.;0WK:.'kWXc.dNWk'cNWXOkOkx;..,kWK:'xWMM\n" +
            "NOc..,oONWWWWXo..;;..;c,dWWd..kWWO::0WXc.:KM0; ,0WK:.xWWx.:XWXc........;0WO,,0WW\n" +
            "o..,dKWXxlkNWMK:..ccoXk;xWNo.'OWXl.;0WK;.:XMK;.:KMK;'OMWd.:KWNd'.'co;...dWXc.oNW\n" +
            ":..oNMNl. ;KWWXc;ONKKKc,OWNl.;0MX:.:KM0; ,0WNo.lXW0,,OWWKO0KKWNKKXXK0kodKWK:.cXM\n" +
            "l..oNMXc..;KWW0:oNWNO;.,0MXc.:KMK;.cXWXdc;oXWXOKWWO,.l0XKkl',lxkko:';ok00kc..oNW\n" +
            "l..oNWX:..cXWWx,oNW0;..;0WK:.cXW0,.oNWN0x:.:dxddXMO,...,'..;;......:c;.....'o0KK\n" +
            "c..xWMK;.'kWW0;.xWWd...:KMK:.oNWO'.,oxl,.......:XWk'.:lcld0NX0kxxOKNWX0kxxkKN0xx\n" +
            ":..kMM0;.oNW0:.'OMNl...cXMNOldKkc........:kxlclONXl.'OWWWWMMWWWWMMMWWWWMMMWWWNXX\n" +
            ";.'kWW0ldNNk;..,0WXc...lXWXd,'...;lkOd,..'lOKXXXOl..lXMMMWWWWMMWWWWWMMWWWWMMMWWW\n" +
            ";.,OWWNNN0c.''.;KWK:...'cc,..;ok0NWMWW0l;'..',,'..'oKWWMWWWWWMMWWWWWMMWWWWWMWWWW\n" +
            ",.;0MMNkc''lOo.cXMK;..:;,;cd0NMMMWWWWMMWNKkdollloxKWMWWWWWMMWWWWMMMWWWWMMMWWWWMM\n" +
            "'.;KWWx..:ONNo.lKOc..cKNXNWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "..:KWNo..xWWXl.',.,lkXWWWWMMMWWWWMMMWWWWMMMWWWWWMMWWWWMMMWWWWMMWWWWWMMWWWWMMMWWW\n" +
            "..cXMNl.'OMMNx,,lkXWWWWWMMWWWWMMWWWWWMMWWWWWWMMWWWWMMWWWWWMMWWWWMMMWWWWMMWWWWWMM\n" +
            "..lNMXc.,0MWWWXXWMWWWWWMMWWWWWMMWWWWWMMWWWWWWMWWWWWWMWWWWWMWWWWWWMWWWWWMMWWWWWWM\n" +
            "..oNWK:.;0WWWMMMWWWWMMMWWWMMMWWWWMMMWWWWMMMMWWWMMMWWWWMMMWWWWMMWWWWMMMWWWWMMMWWW\n" +
            "..xXOc..cXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
            "..;;.'ckXWMMMWWWWMMWWWWMMMWWWWMMWWWWWMMWWWWWMMMWWWWMMMWWWWMMWWWWMMMWWWWMMWWWWMMM\n" +
            "l...:kNMWWWWWWWWWWWWMMWWWWWMMWWWWWMWWWWWWMMWWWWWMMWWWWWMWWWWWMMWWWWWMMWWWWWMWWWW\n";

    public static String trophy = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNWMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMNo;llllllllloollollollllollollollooloool;lXMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMWMX:;KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXc;KWWWWWWWWWWWMMMMMMM\n" +
            "MMMMMMWOlloooooooool,cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,coooooooolckWMMMMMM\n" +
            "MMMMMMWl'd00OOOOOOOO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00000000KKx'cNMMMMMM\n" +
            "MMMMMMWo,OM0lcooloolcoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXocloollc:kW0,oWMMMMMM\n" +
            "MMMMMMMx,xWx'oKKKKKKl,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,oXXXXXx'oWx,xWMMMMMM\n" +
            "MMMMMMM0;lNk,dWMMMMMk,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,OMMMMWx,xNl,OMMMMMMM\n" +
            "MMMMMMMNl;0K;cNMMMMMK;lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc;KMMMMNl;0K;cNMMMMMMM\n" +
            "MMMMMMMMO,oXo,OMMMMMNc;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;lNMMMM0;lXd,kMMMMMMMM\n" +
            "MMMMMMMMNo,OK::XMMMMWx,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,kWMMMXc;0O,lNMMMMMMMM\n" +
            "MMMMMMMMMXc;0O;lXMMMMX::XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX::XMMMXl;k0::KMMMMMMMMM\n" +
            "MMMMMMMMMMKc;OO::OWMMWx,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,xWMW0c:kO:cKMMMMMMMMMM\n" +
            "MMMMMMMMMMMXo;d0d:lOXWNl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:cXNOl:oOd;oXMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMWOc:xOdlcloc.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.;lcldOx:ckNMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMNklcoxkkxdoxXMMMMMMMMMMMMMMMMMMMMMMMMMMMNkdxkkxoclkNWMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMWKkollooddxkXMMMMMMMMMMMMMMMMMMMMMMMNkdooollokKWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMWX0Oxxo::0WMMMMMMMMMMMMMMMMMMMWKc;okO0XWMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMXo;dXWMMMMMMMMMMMMMMMMNx:lKWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc:xXMMMMMMMMMMMMMNOc:kNMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc:dKWMMMMMMMWXxccxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoclkNMMMW0o:lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX:,0MMMNl,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo,0MMMNc;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo,OMMMNl;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMWX00000000000:'d000O;'x000000000XWMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMNl,looooooooolcloollccloooooool,cXMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMWXKKO;;OKKKKKKKKKKKKKKKKKKKKKKKKKKO;,OKKXNMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMWx;col::llllllllllllolllllllllllllll::lol;lXMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMM0;lNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx,xWMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMNl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX::KMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMk,oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,dWMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMXc:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc;KMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMWx.;xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd:.dWMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMW0dodddddddddddddddddddddddddddddddddddddddddddd0WMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n";


}


